### ISSUE TITLE
Fancy UI (please split as desired)

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#18]
* [glass: come up with a better name or keep using glass](https://github.com/aquarists-labs/planning-and-discussion/issues/7)
* [glass: create a repository for the frontend and bootstrap it with a angular](https://github.com/aquarists-labs/planning-and-discussion/issues/8)
* [glass: start implementing a frontend for the bootstrapping of the ceph cluster](https://github.com/aquarists-labs/planning-and-discussion/issues/9)
* [glass: create a login page](https://github.com/aquarists-labs/planning-and-discussion/issues/11)
* [glass: create a dashboard](https://github.com/aquarists-labs/planning-and-discussion/issues/12)

**Comment by s0nea** [comment]
I'm going to close the issue because of two reasons:

- The "sub-issues" are no longer accessible due to repository changes. E.g. issue regarding the login page has been moved from https://github.com/aquarists-labs/planning-and-discussion/issues/11 -> https://github.com/aquarist-labs/aquarium/issues/23
- All mentioned issues are either unnecessary, already done or tracked and prioritized elsewhere.

Please feel free to re-open and update the issue if you think we do need it as an overview of the mentioned "sub-issues".
