### ISSUE TITLE
test: Set up CI/CD for labs

### ISSUE THREAD

**Issue by asettle** [aquarist-labs/aquarium#20]
CI/CD needs to be setup for labs.

Requirements are not known at this time - this needs to be investigated further.

**Comment by kshtsk** [comment]
Maybe we split this issue into separate ci tickets:
- setup unit test github actions
- setup static analysis (lint?)
- setup deployment or smoke test.

Or we should keep discussion what and how many layers of integration test we should have?

**Comment by jhesketh** [comment]
> Maybe we split this issue into separate ci tickets:
> 
>     * setup unit test github actions
> 
>     * setup static analysis (lint?)
> 
>     * setup deployment or smoke test.
> 
> 
> Or we should keep discussion what and how many layers of integration test we should have?

Happy to split it into separate issues, but item 1+2 are otherwise already done so we can just leave this as discussion on setup deployment and smoke tests.

**Comment by kshtsk** [comment]
Submitted a script for testing deployment what we have at the moment as a separate repo https://github.com/aquarist-labs/wasser

Corresponding config is on its way to merge to main branch of aquarium https://github.com/aquarist-labs/aquarium/pull/265

For now it is setup as a jenkins job and defined based on the example https://github.com/aquarist-labs/wasser/blob/main/examples/jjb/aquarium.yaml

We enable it as automatic run for each PR.

The workflow is to check steps from https://github.com/aquarist-labs/aquarium/blob/main/doc/from-zero-to-hacking.md
with minor changes to make it working on openSUSE Leap 15.2 host.

On Tumbleweed it does not work for me at the moment, since system is slightly different.

Since we're doing CI, which is a development process and evolves as far as the product developed, and system is constantly improves as well as new requirements appears, and initial setup is done we are ready to close this ticket as soon as #265 is merged. All further improvements suggests should be handles as separate 'issues'.

**Comment by kshtsk** [comment]
Closing this, for new features there should be specific issue opened.
