### ISSUE TITLE
vagrant: don't share via NFS but copy files

### ISSUE THREAD

**Issue by l-mb** [aquarist-labs/aquarium#218]
If we copied the files to the guest/VMs entirely (and made that easier to sync after changes), that would remove the need for the NFS setup rules and sudo rights.

Is that a good idea?

**Comment by tserong** [comment]
See https://www.vagrantup.com/docs/synced-folders - we could switch it to rsync if NFS is undesirable for some reason. Or it can be turned off entirely by getting rid of the relevant `config.vm.synced_folder` line in tests/vagrant/templates/Vagrantfile.tmpl.

I'm curious to know how people are using this feature of Vagrant ATM - the idea is it gives you the source tree inside the running VM, and doing that over NFS is neat because anything you change is changed immediately, there's no sync to worry about. That said, inside the VM, aquarium by default is activated by systemd and runs code under /usr/share/aquarium, not /srv/aquarium (which is where the source tree is mounted), so I guess you'd `systemctl stop aquarium` then `/srv/aquarium/run_aquarium.sh` if you wanted to run it inside the VM direct from the source tree, and be able to make live edits?

For someone who's not actively hacking on the code, live, in the VM (e.g. someone who just wants to run aquarium to see what it's like) the shared folder is probably of no or little interest. Maybe it should be turned off by default, with an option to `aqrdev create` which turns it on if needed?
