### ISSUE TITLE
gravel: /orch/hosts returns Host model with hostname == address

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#224]
The given REST API endpoint seems to response a Host model where hostname is equal to the address. See https://user-images.githubusercontent.com/1897962/109295129-83ccd500-782e-11eb-95a4-92545dcf25e0.png

```
[
	{
		"hostname": "node01",
		"address": "node01"
	}
]
```

**Comment by jecluis** [comment]
@theanalyst are you still working on this?  :)

**Comment by jecluis** [comment]
This seems to come from the orchestrator itself. Apparently, somehow, the orchestrator sets the initial node's address as `node01`, which is resolvable within `node01` to `127.0.0.1`.

However, upon adding a new host this behavior no longer shows, so it might just happen that this is some weird corner case on bootstrap. @mgfritch does this ring any bells?

**Comment by jecluis** [comment]
Turns out this might be a feature/bug in cephadm, as it is adding the first host as `ceph orch host add <name>` without specifying an ip address. Opened a PR upstream (https://github.com/ceph/ceph/pull/40463) to, hopefully, deal with it there. In the meantime, we might want to diverge from upstream to have this fixed -- but let's wait for pacific to drop before we do that.

**Comment by jecluis** [comment]
closing as it is fixed for us; we should update our version of ceph with #389
