### ISSUE TITLE
Remove node roles (i.e. no leaders, no followers, everything is just an Aquarium node)

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#268]
This is resulting from discussion in https://github.com/aquarist-labs/aquarium/pull/266#issuecomment-793513870. Right now (2021-03-09) the first node bootstrapped is the Leader and other nodes are Followers, and need to join the cluster by talking to that Leader. I'd like to ideally remove this concept, so that any new node can talk to any existing node to join the cluster, i.e. there's no concept of a leader or followers, except perhaps for the duration of a join (where the joining node may need to have a brief discussion with whichever node it's talking to in order to actually do the join), but with that exception, every node is equal, and effectively stateless. If we need to know which nodes are present, we can ask Ceph. If Ceph is down, well, we can't add new nodes anyway, so the list of existing nodes becomes somewhat moot at that point ;-)

Note that this issue relates to https://github.com/aquarist-labs/aquarium/issues/32 - just because I'd like everything to be stateless, doesn't mean we don't somehow need to share state...

**Comment by jecluis** [comment]
So, my reasoning, aside from manifests and what not, is that, at some point, we'll need to address #86 , #87, and the discussion from https://github.com/aquarist-labs/forum/discussions/2 .

So there's a very good chance that we'll need a single node to deal with the resource constraints and the user's requirements, reconcile them, and then perform the necessary operations. That will definitely require persistent state (and I'd keep arguing for it to be dissociated from Ceph, but I don't particularly have a strong opinion at the moment), and a selected node to perform those operations -- otherwise we might end up with all nodes doing the same.

**Comment by tserong** [comment]
Yes, we definitely need to address those things. I'm just hoping we can somehow find a way to do that without adding an extra layer that involves some sort of special individual node, because that doesn't make the problem any easier, it just moves it from one layer to another :-/

**Comment by tserong** [comment]
> Have all nodes to sync from the internet, or require an external time server on the network?

Sure, why not? By default, chrony will sync from the internet, so there's nothing we need to do. Anyone who doesn't want that (or can't do that due to lack of internet access) needs to specify a separate server or servers to use, but those people presumably already know how to do that sort of configuration.

I wouldn't want one of the cluster nodes to be the time source anyway -  again, it makes that node special somehow.

**Comment by jecluis** [comment]
Maybe I keep thinking about Aquarium, a bit too much, as a very simplified version of Ceph, and that is probably affecting my judgement here. Still, I think from a user's point of view, even a power user, should not have to specify a time server on every new node. The node should just join the cluster and be useful, aside, maybe, from specifying hostname and the network interface in case there are multiple. And that requires state to be kept somewhere.

Whether this state is kept on a leader, or on every available node and kept in sync somehow, I don't know. The former is simpler, because we have someone to gate updates and keep them consistent.

As for the lack of a manifest, I'd still argue we need one based because, even if Ceph is down, we probably want to know which hosts we have and where they are. Can this just be cached from Ceph? Probably. But right now I'm at a point where I don't know exactly what might be needed in the future, and I'm not entirely sure relying solely on Ceph is the way to go exactly because of that. Thoughts on that would be appreciated and a lot more useful for planning than my gut feelings.

**Comment by tserong** [comment]
> Still, I think from a user's point of view, even a power user, should not have to specify a time server on every new node. The node should just join the cluster and be useful, aside, maybe, from specifying hostname and the network interface in case there are multiple. And that requires state to be kept somewhere.

In the case of time sync config, we presumably want all nodes to be the same. I wonder if it would make sense to, on join, "just" pull /etc/chrony* from an existing node? That way, provided it's configured correctly on the bootstrap node, it'll end up configured the same on all other nodes as they're added (I realise that doesn't help with updating configuration later, if someone decides to change the chrony config, but it would get everything set up initially easily).

> As for the lack of a manifest, I'd still argue we need one based because, even if Ceph is down, we probably want to know which hosts we have and where they are. Can this just be cached from Ceph? Probably. But right now I'm at a point where I don't know exactly what might be needed in the future, and I'm not entirely sure relying solely on Ceph is the way to go exactly because of that. Thoughts on that would be appreciated and a lot more useful for planning than my gut feelings.

For the manifest question specifically, I'm in favour of treading Ceph as the source of truth for information about what nodes are and aren't present, and having Aquarium cache that if necessary to handle the case where the cluster is down. IMO this holds for anything that is configured in the Ceph orchestrator / cephadm (or in general, in Ceph itself), because Ceph wants to be managing that stuff.  If we find we need something beyond that in future, then my inclination is to create that thing once we're certain we need it.  If it helps, the perspective I'm approaching this from is to think about ways to build the _least_ scaffolding/infrastructure possible in Aquarium...  So even if we do need to have a special leader node concept, and our own separate config store / sync thing to enable some super-awesome Aquarium functionality, I'd _still_ rely on Ceph for the bits it's actually notionally in charge of (e.g. the node manifest).

(Hopefully I'm

**Comment by tserong** [comment]
Oh, a further thought, speaking of gut feelings ;-) If we're able to remain stateless/leaderless/followerless _now_, my guess is it's easier to later add state/leader/follower if we really need to, than the reverse (i.e. if we have a leader now and are operating "clusters all the way down" style, and later realise we need to get rid of that thing and go "stateless", ripping it out is going to be a PITA).

**Comment by jecluis** [comment]
Fair points. I think it's easy enough to strip the leader/follower concept at this point. It's not doing much, really, aside from gating certain features (e.g., don't handle join messages if you're not a leader). I'd say we can look at that after merging #266 ?

**Comment by jecluis** [comment]
So, technically, going stateless also means we'll have a working dashboard on any node. And that means any gravel needs to be able to provide the same information through the API. I have this nagging feeling that there's something that's not going to play out well with that, but can't recall what it is, so I guess that's something we can kick down the road until we actually hit that particular wall (if ever).

**Comment by tserong** [comment]
> Fair points. I think it's easy enough to strip the leader/follower concept at this point. It's not doing much, really, aside from gating certain features (e.g., don't handle join messages if you're not a leader). I'd say we can look at that after merging #266 ?

Fine by me :-)
