### ISSUE TITLE
Include containers necessary for initial deployment inside Aquarium image

### ISSUE THREAD

**Issue by tserong** [aquarist-labs/aquarium#457]
When deploying Ceph on each node[1], the ceph container image is pulled from (at the time of writing) docker.io/ceph/ceph:v16. That takes a certain amount of time (and also an internet connection).

Once #449 is merged, we'll also be pulling quay.io/coreos/etcd:latest, and that presumably needs to complete before Aquarium can actually be used at all.

I assume there may be other containers in future too.

So, I had a crazy idea. Can we do a `podman pull` of all necessary containers at image build time, so that they are present and ready to use immediately inside Aquarium?

[1] Actually, it looks like the ceph container is pulled automagically at runtime _before_ deployment, I assume as a result of Aquarium periodically running `cephadm gather-facts` and/or `cephadm inventory`, but the point still stands, this requires a certain amount of time, and an internet connection.

**Comment by jecluis** [comment]
There's just one problem I see with packaging the containers as well: we're tying Ceph upgrade to image upgrade.

While I'm all in favor of supplying the containers for the reasons you provided, I worry that tying updating containers to an image update might be annoying because, should we want to upgrade Ceph but not Aquarium, we would have to provide an image just with updated containers. Or tell the user "okay, we provide you with the initial containers and all, but upgrades need an internet connection or a local registry". And then we are kind of breaking the appliancy feel, because our image no longer is able to handle that stuff for the user.

I think it might be okay to go with the latter though. Just provide the images for the initial deployment, but then have the user relying on an internet connection or local registry, and have Aquarium refusing to use its own images if an existing cluster is detected.

Also, this will likely mean we'll have to copy those images to the state partition/mount on initial node deployment.

**Comment by tserong** [comment]
> I think it might be okay to go with the latter though. Just provide the images for the initial deployment, but then have the user relying on an internet connection or local registry, and have Aquarium refusing to use its own images if an existing cluster is detected.
> 
> Also, this will likely mean we'll have to copy those images to the state partition/mount on initial node deployment.

Yeah, my thought was that this would only be for initial deployment, and we'd use the state partition thereafter, which (hopefully) makes the upgrade problem go away. Even easier maybe if the state partition can be overlaid/bind mounted/however-that-works on top of the running aquarium image.
