### ISSUE TITLE
gravel: How will we store statistics? 

### ISSUE THREAD

**Issue by asettle** [aquarist-labs/aquarium#497]
---

**What is your question?**
How are we going to store statistics?

**More details**
I think that's relatively self-explanatory but you never know.

**Comment by tserong** [comment]
What statistics do we need to store, and why? Or, to put that another way: what _isn't_ ceph already giving us on this front?

**Comment by jecluis** [comment]
I believe the question is less about what to store, but how we're storing them.

I'm assuming that, when we deploy prometheus with Ceph, we're keeping persistent state for prometheus somewhere in a cluster pool. Should this assumption be correct, we can tolerate the failure of the server prometheus is running by starting a different instance somewhere else. There is still a question how we'd then find the new instance, but that's something that can be addressed by keeping its address somewhere in etcd or something.

Should that assumption be wrong, then we'd be losing prometheus state should that instance go down. This is, after all, prometheus default behavior (he said, crying over 6 months of lost energy metering statistics).

But okay, we're keeping that data somewhere safe in the cluster and we can magically spin up another prometheus instance, and we get our statistics back.

The question now is: do we want to keep statistics access even if we lose quorum? Do we find that the benefit of having access to those statistics outweigh the additional burden of maintaining prometheus ourselves, and storing that data in the system disk?

If we go with "yes", then we have an additional problem: how do we ensure we get the statistics across the cluster, in case of host failure? We'd now be relying on a single instance's system disk, no access to a distributed storage system. Maintaining that kind of replication would likely entail setting up something like cortex (https://cortexmetrics.io). Which is yet another cluster we'd have to maintain.

Is it worth it?

**Comment by p-se** [comment]
> What statistics do we need to store, and why? Or, to put that another way: what _isn't_ ceph already giving us on this front?

Ceph isn't giving us a way to store metrics as historical data. It offers current data through librados and metrics through the Prometheus mgr module.

> I believe the question is less about what to store, but how we're storing them.

cephadm has the capability to deploy an highly available Prometheus/Alertmanger/Grafana stack already. It does not utilize any cluster storage and hence isn't endangered to fail when the cluster isn't working as expected. It, however, is a highly available setup, due to the Prometheus instances scraping and storing their metrics completely independent from each other. Should two Prometheus nodes be used for monitoring and should we lose those two, then the data would be lost. If, however, only one instance is lost, the historical data would still be there. At that point it might be a good idea to spin up second instance again, which would have to start over with the data, so we'd end up with one instance having "all" the data and one instance with just a few minutes. But...

A few days of data is usually sufficient to even foresee and alert on upcoming issues. By default, Prometheus stores 15 days of data and drops everything that's older than that. Prometheus does not have a problem with storing data longer than those 15 days, but if done so with Prometheus, the required capacity can raise rather quickly. And even with no historical data, monitoring can be quite useful. Losing historical data doesn't necessarily mean to lose monitoring capabilities, if additional instances can be added.

Note that I've [described the HA setup of Prometheus/Alertmanager/Grafana and Ceph Dashboard in another issue.](https://github.com/aquarist-labs/aquarium/issues/89#issuecomment-779110879) The _Notes on configuration_ section might be most interesting in this context.

Because we'd get so much for free by simply using what cephadm already offers us, which is an HA setup that would work without quorum or even if the cluster is down, I'd recommend to use that. There are downsides to that, but Prometheus isn't meant to be used as long term storage, although it could be. There's no issue other than increased disk space usage if we decided to store metrics longer than those 15 days. Prometheus will keep working when metrics are stored longer, but the most efficient way to store metrics persistently would to be to reduce the resolution of the data (and probably use additional software). Should we get to the point where we find ourselves needing that, we can still adapt and add additional software at that point.
