### ISSUE TITLE
glass: per-host osd usage heatmap widget

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#501]
Something like this:

![image](https://user-images.githubusercontent.com/506918/118435225-15c9d880-b6ce-11eb-8cbb-04d9aab25d96.png)

But for OSDs, per host, instead of contributions per Month.

The stronger the color, the higher the usage.

**Comment by jecluis** [comment]
@votdev how feasible is this?

**Comment by votdev** [comment]
> @votdev how feasible is this?

From the implementation point of view there shouldn't be a problem, we can draw it ourself or use chartjs with a plugin (after adapting the [plugin](https://github.com/ZephyrHQ/chartjs-heatmap) to v3) or use the [ngx-charts heatmap](https://swimlane.gitbook.io/ngx-charts/examples/heat-map-chart).

But i'm asking myself if we want to display that data because it shows Ceph related things. Didn't we want to abstract/hide that from the user in Aqarium?

**Comment by jecluis** [comment]
Yeah, I guess we'd be showing per-disk, instead of per-osd. I think showing that kind of information can be relevant, especially because we can also color them red if they are failed, or down, or whatever.

**Comment by votdev** [comment]
I think all information is already available via the [/devices](https://github.com/aquarist-labs/aquarium/blob/main/src/gravel/api/devices.py#L31) endpoint, right? The frontend only needs to do some fancy calculation and render the information.
