### ISSUE TITLE
glass: failed to apply swimlane/ngx-charts patch

### ISSUE THREAD

**Issue by s0nea** [aquarist-labs/aquarium#517]
Running `./tools/setup-dev.sh` displays the following error:

```
> glass@0.0.0 postinstall /home/user/src/aquarium/src/glass
> patch-package; ngcc

patch-package 6.4.7
Applying patches...

**ERROR** Failed to apply patch for package @swimlane/ngx-charts at path
  
    node_modules/@swimlane/ngx-charts

  This error was caused because patch-package cannot apply the following patch file:

    patches/@swimlane+ngx-charts+17.0.1.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package @swimlane/ngx-charts
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
    

---
patch-package finished with 1 error(s).

```

**Comment by votdev** [comment]
This happens if the `node_modules` directory already exists. `npm install` has a `postinst` script that is patching the `@swimlane/ngx-charts` module on package installation. If you run the command twice, then patching fails as expected. 

To fix that issue we need to ensure `node_modules` is removed before running `npm install`. Same happens when [building the image](https://github.com/aquarist-labs/aquarium/pull/530).

**Comment by votdev** [comment]
Fix has been attached to https://github.com/aquarist-labs/aquarium/pull/530.
