### ISSUE TITLE
gravel: SSL support

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/aquarium#90]
Investigate securing HTTP connections to our dashboard with SSL or TLS. Consider:

- Creating self-signed certs (this would probably be the easiest option)
- Using certs signed by CA (enable to the ceph mgr?) 
- Enable by default? How to disable SSL?

**Comment by tserong** [comment]
Additionally, as mentioned the other day, we should look at maybe using default ports (80 & 443), just to make life slightly easier when pointing a web browser at an Aquarium instance.

The one catch is that 80 & 443 might conflict with RGW, once we eventually support deploying that. Suggestions to fix this include:

* Always configure RGW to run on some other port instead of 80/443 (trivial but might be undesirable).
* Bind Aquarium to 80/443 during bootstrap, but also bind to a couple of other ports (8080/8443/whatever), then if someone wants to use RGW later on 80/443, tell 'em Aquarium is still available on the other ports.
* Somehow magically determine whether or not the client wants aquarium or RGW and redirect as appropriate.
  * By user-agent? (dicey, ugh...)
  * I wonder if doing it by hostname would work, like, have a transparent proxy check the Host HTTP request header, and if it's the system hostname, serve aquarium, but if it looks like an RGW realm(?) name, serve RGW? (is this completely nuts?)

**Comment by AvengerMoJo** [comment]
I am using https://certbot.eff.org/. It is a free SSL cert as long as you running update every month.
Instead of self sign I think we can automated this certbot process. In addition, this could be our first 3rd parties service we can proxy our customer to purchase a 3rd party signed cert as well?

**Comment by asettle** [comment]
Moved
